### ISSUE TITLE
Thermocouple I2C

### ISSUE THREAD

**Issue by Esouder** [UBC-Rocket/WB-DAQ-Firmware#35]

**Comment by br-zhou** [comment]
Found last working commit for I2C: 9d683f480690ab93fbb5d05b615fba2df73f52eb
Found first compilable commit where I2C is not working: 0b09ca612769c21db0a07016b56a051a13c445c6

Since no I2C Fireware code was chanced between these two commits, we are investigating the changes in the Peripheral Drivers between the two commits, which appears to have deleted relevant I2C code.

**Comment by br-zhou** [comment]
Made I2C work on latest git commit. 
Issue was in the WB-DAQ-Firmware.mex file, in which the I2C peripherals were deleted.

**Comment by br-zhou** [comment]
NOTE: The TC at address 0b1100000 on I2C1 for the **old** DAQ Board is not working like the rest of the TCs. The chip seems to update the register at 1/4th the frequency of the other TCs.
